CREATE TABLE telefone (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	ddd VARCHAR(3) NOT NULL,
	numero VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE pessoa_telefone (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	telefone_id bigint NOT NULL,
	pessoa_id bigint NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;